# .streamlit/secrets.toml
OPENAI_API_KEY = "sk-proj-iueggGhpjzF9KcY5gKO5T3BlbkFJzyv6O7TYng929TLRkMNP"

[connections.snowflake]
user = "azhang"
authenticator=EXTERNALBROWSER
warehouse = "COMPUTE_WH"
role = "ACCOUNTADMIN"
account = "AVB03750"
